Add works and about me section
BranBayou/Mobile-First-Portfolio-Project pull request #2
Opened 2023-02-17 18:37 UTC by BranBayou

I created a new branch  Works-and-aboutMyself-section and I added works and about me sections.

2023-02-17 19:16 UTC, franclobo requested changes
Hi @BranBayou, 

# Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/219766132-8eeea952-1623-49ad-9ba1-b3c132cb6c5a.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Good use of tags ✔️ 
- Best practices of HTML & CSS 💯 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 19:16 UTC, franclobo commented on styles.css
> +}
- [ ] Please 🙏🏽 align the content of the card to match the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/219761724-06cc7ddc-d44a-417a-860a-2430a32b32b0.png) | ![image](https://user-images.githubusercontent.com/58642949/219762040-93d026b4-fd2e-43a5-8ae4-1e8dbeeb843a.png) |

2023-02-17 19:16 UTC, franclobo commented on styles.css
> +}
- [ ] Please 🙏🏽 add the correct space between the skills buttons and the see project button and correct the background color of the button it is #fff to be similar to the Figma template 👇🏽 

| Figma template | Your template |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/219762787-0794f2e8-f762-4b77-be15-143ddcbfdf56.png) | ![image](https://user-images.githubusercontent.com/58642949/219762930-0abadb7d-e642-43a0-86c9-a369d8e5864c.png) |

2023-02-17 19:16 UTC, franclobo commented on styles.css
>  }
- [ ] Please 🙏🏽 add a space between the bullet points and the title and a space at the end to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/219765906-383146ab-7e0b-4787-b74c-63f14b7c65c2.png) | ![image](https://user-images.githubusercontent.com/58642949/219765981-344a6314-1120-4966-97cb-c8a33ceee624.png) |

2023-02-18 02:05 UTC, emmiiorji approved these changes
Hi @BranBayou, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Good Highlights✔️

- Requested changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 02:14 UTC, emmiiorji requested changes
Hi @BranBayou, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 02:14 UTC, emmiiorji commented on styles.css
> +}
As requested by the previous reviewer, kindly adjust the space between the bullets and the titles and at the end of the section in order to follow the design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/219826349-638f1313-61e7-40a5-baa0-943c6bdc4cf1.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/219826377-a4601d96-6a09-4a84-9fc6-8f600b7e3ddf.png)

2023-02-18 03:16 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @BranBayou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 03:28 UTC, merged